name: Daily Superstore Data Update

on:
 workflow_dispatch: # मॅन्युअली रन करण्यासाठी
 schedule:
    - cron: '30 3 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install pandas numpy google-api-python-client google-auth gdown

      - name: Run Python Script
        env:
          GDRIVE_TOKEN: ${{ secrets.GDRIVE_TOKEN }}
          GDRIVE_FILE_ID: ${{ secrets.GDRIVE_FILE_ID }}
        run: python script.py
